# SPDX-FileCopyrightText: 2020-2024 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: "Thanks for opening your first pull request in this repository! :v:"
