# SPDX-FileCopyrightText: 2020-2024 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

version: 2
updates:
  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directories:
      - "/"
      - "/vendor-bin/coding-standard"
      - "/vendor-bin/openapi-extractor"
      - "/vendor-bin/php-coveralls"
      - "/vendor-bin/php-scoper"
      - "/vendor-bin/phpunit"
      - "/vendor-bin/psalm"
      - "/vendor-bin/rector"
      - "/tests/integration"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
