# SPDX-FileCopyrightText: 2020-2025 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Added'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'

  - title: 'Changed'
    labels:
      - 'chore'
      - 'refactor'
      - 'improvement'

  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: 'Removed'
    labels:
      - 'removed'
      - 'deprecated'

  - title: 'Security'
    labels:
      - 'security'

  - title: 'Tests'
    labels:
      - 'test'

  - title: 'Dependencies'
    labels:
      - 'dependencies'

  - title: 'Documentation'
    labels:
      - 'docs'

  - title: 'Other'
    labels: []

change-template: '- $TITLE [#$NUMBER]($URL)'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## [$RESOLVED_VERSION] – $DATE

  $CHANGES

  **Full Changelog:** https://github.com/LibreSign/libresign/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
