/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate/cfssl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate certificate using CFSSL engine
         * @description This endpoint requires admin access
         */
        post: operations["admin-generate-certificate-cfssl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate/openssl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate certificate using OpenSSL engine
         * @description This endpoint requires admin access
         */
        post: operations["admin-generate-certificate-open-ssl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate/engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set certificate engine
         * @description Sets the certificate engine (openssl, cfssl, or none) and automatically configures identify_methods when needed
         *     This endpoint requires admin access
         */
        post: operations["admin-set-certificate-engine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load certificate data
         * @description Return all data of root certificate and a field called `generated` with a boolean value.
         *     This endpoint requires admin access
         */
        get: operations["admin-load-certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/configure-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check the configuration of LibreSign
         * @description Return the status of necessary configuration and tips to fix the problems.
         *     This endpoint requires admin access
         */
        get: operations["admin-configure-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/signature-background": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get custom background image
         * @description This endpoint requires admin access
         */
        get: operations["admin-signature-background-get"];
        put?: never;
        /**
         * Add custom background image
         * @description This endpoint requires admin access
         */
        post: operations["admin-signature-background-save"];
        /**
         * Delete background image
         * @description This endpoint requires admin access
         */
        delete: operations["admin-signature-background-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload new certificate policy PDF for this instance
         * @description This endpoint requires admin access
         */
        post: operations["admin-save-certificate-policy"];
        /**
         * Delete certificate policy of this instance
         * @description This endpoint requires admin access
         */
        delete: operations["admin-delete-certificate-policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/certificate-policy/oid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update OID
         * @description This endpoint requires admin access
         */
        post: operations["admin-update-oid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/admin/active-signings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of files currently being signed (status = SIGNING_IN_PROGRESS)
         * @description This endpoint requires admin access
         */
        get: operations["admin-get-active-signings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/crl/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List CRL entries with pagination and filters
         * @description This endpoint requires admin access
         */
        get: operations["crl_api-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/crl/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a certificate by serial number
         * @description This endpoint requires admin access
         */
        post: operations["crl_api-revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/footer-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get footer template
         * @description Returns the current footer template if set, otherwise returns the default template.
         *     This endpoint requires admin access
         */
        get: operations["footer_template-get-footer-template"];
        put?: never;
        /**
         * Save footer template and render preview
         * @description Saves the footer template and returns the rendered PDF preview.
         *     This endpoint requires admin access
         */
        post: operations["footer_template-save-footer-template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/policies/system/{policyKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read explicit system policy configuration
         * @description This endpoint requires admin access
         */
        get: operations["policy-get-system"];
        put?: never;
        /**
         * Save a system-level policy value
         * @description This endpoint requires admin access
         */
        post: operations["policy-set-system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/policies/user/{userId}/{policyKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an explicit user-level policy for a target user (admin scope)
         * @description This endpoint requires admin access
         */
        get: operations["policy-get-user-policy-for-user"];
        /**
         * Save an explicit user policy for a target user (admin scope)
         * @description This endpoint requires admin access
         */
        put: operations["policy-set-user-policy-for-user"];
        post?: never;
        /**
         * Clear an explicit user policy for a target user (admin scope)
         * @description This endpoint requires admin access
         */
        delete: operations["policy-clear-user-policy-for-user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/libresign/api/{apiVersion}/setting/has-root-cert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Has root certificate
         * @description Checks whether the root certificate has been configured by checking the Nextcloud configuration table to see if the root certificate settings have
         */
        get: operations["setting-has-root-cert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        ActiveSigningItem: {
            /** Format: int64 */
            id: number;
            uuid: string;
            name: string;
            signerEmail: string;
            signerDisplayName: string;
            /** Format: int64 */
            updatedAt: number;
        };
        ActiveSigningsResponse: {
            data: components["schemas"]["ActiveSigningItem"][];
        };
        Capabilities: {
            features: string[];
            config: {
                "show-confetti": boolean;
                "sign-elements": {
                    "is-available": boolean;
                    "can-create-signature": boolean;
                    /** Format: double */
                    "full-signature-width": number;
                    /** Format: double */
                    "full-signature-height": number;
                    /** Format: double */
                    "signature-width": number;
                    /** Format: double */
                    "signature-height": number;
                };
                envelope: {
                    "is-available": boolean;
                };
                upload: {
                    /** Format: int64 */
                    "max-file-uploads": number;
                };
            };
            version: string;
        };
        CertificateDataGenerated: components["schemas"]["EngineHandler"] & {
            generated: boolean;
        };
        CertificateEngineConfigResponse: {
            engine: string;
            identify_methods: components["schemas"]["IdentifyMethodSetting"][];
        };
        CertificatePolicyResponse: {
            /** @enum {string} */
            status: "success";
            CPS: string;
        };
        ConfigureCheck: {
            message: string;
            resource: string;
            /** @enum {string} */
            status: "error" | "success";
            tip: string;
        };
        ConfigureChecksResponse: components["schemas"]["ConfigureCheck"][];
        CrlListItem: {
            /** Format: int64 */
            id: number;
            serial_number: string;
            owner: string;
            /** @enum {string} */
            status: "issued" | "revoked";
            certificate_type: string;
            engine: string;
            instance_id: string | null;
            /** Format: int64 */
            generation: number | null;
            issued_at: string | null;
            valid_to: string | null;
            revoked_at: string | null;
            /** Format: int64 */
            reason_code: number | null;
            comment: string | null;
            revoked_by: string | null;
            invalidity_date: string | null;
            /** Format: int64 */
            crl_number: number | null;
        };
        CrlListResponse: {
            data: components["schemas"]["CrlListItem"][];
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            length: number;
        };
        CrlRevokeResponse: {
            success: boolean;
            message: string;
        };
        EffectivePolicyResponse: {
            policy: components["schemas"]["EffectivePolicyState"];
        };
        EffectivePolicyState: {
            policyKey: string;
            effectiveValue: components["schemas"]["EffectivePolicyValue"];
            sourceScope: string;
            visible: boolean;
            editableByCurrentActor: boolean;
            allowedValues: components["schemas"]["EffectivePolicyValue"][];
            canSaveAsUserDefault: boolean;
            canUseAsRequestOverride: boolean;
            preferenceWasCleared: boolean;
            blockedBy: string | null;
            /** Format: int64 */
            groupCount: number;
            /** Format: int64 */
            userCount: number;
        };
        EffectivePolicyValue: (boolean | number | string | {
            [key: string]: Record<string, never>;
        }) | null;
        EngineHandler: {
            configPath: string;
            cfsslUri?: string;
            policySection: components["schemas"]["PolicySection"][];
            rootCert: components["schemas"]["RootCertificate"];
        };
        EngineHandlerResponse: {
            data: components["schemas"]["EngineHandler"];
        };
        ErrorResponse: {
            error: string;
        };
        FailureStatusResponse: {
            /** @enum {string} */
            status: "failure";
            message: string;
        };
        FooterTemplateResponse: {
            template: string;
            isDefault: boolean;
            template_variables: {
                [key: string]: {
                    description?: string;
                    type?: string;
                    example?: string;
                    default?: string;
                };
            };
            /** Format: int64 */
            preview_width: number;
            /** Format: int64 */
            preview_height: number;
            /** Format: int64 */
            preview_zoom: number;
        };
        HasRootCertResponse: {
            hasRootCert: boolean;
        };
        /** @enum {string} */
        IdentifyMethodRequirement: "required" | "optional";
        IdentifyMethodSetting: {
            name: string;
            friendly_name: string;
            enabled: boolean;
            requirement: components["schemas"]["IdentifyMethodRequirement"];
            /** Format: int64 */
            minimumTotalVerifiedFactors?: number;
            signatureMethods?: components["schemas"]["SignatureMethods"];
        };
        MessageResponse: {
            message: string;
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        PolicySection: {
            OID: string;
            CPS: string;
        };
        PublicCapabilities: {
            libresign?: components["schemas"]["Capabilities"];
        };
        RootCertificate: {
            commonName: string;
            names: components["schemas"]["RootCertificateName"][];
        };
        RootCertificateName: {
            id: string;
            value: (string | string[]) | null;
        };
        SignatureMethod: {
            enabled: boolean;
            label: string;
            name: string;
        };
        SignatureMethodEmailToken: {
            label: string;
            /** @enum {string} */
            identifyMethod: "email" | "account";
            needCode: boolean;
            hasConfirmCode: boolean;
            blurredEmail: string;
            hashOfEmail: string;
        };
        SignatureMethodPassword: {
            label: string;
            name: string;
            hasSignatureFile: boolean;
        };
        SignatureMethods: {
            clickToSign?: components["schemas"]["SignatureMethod"];
            emailToken?: components["schemas"]["SignatureMethodEmailToken"];
            password?: components["schemas"]["SignatureMethodPassword"];
        };
        SuccessStatusResponse: {
            /** @enum {string} */
            status: "success";
        };
        SystemPolicyResponse: {
            policy: components["schemas"]["SystemPolicyState"];
        };
        SystemPolicyState: {
            policyKey: string;
            /** @enum {string} */
            scope: "system" | "global";
            value: components["schemas"]["EffectivePolicyValue"];
            allowChildOverride: boolean;
            visibleToChild: boolean;
            allowedValues: components["schemas"]["EffectivePolicyValue"][];
        };
        SystemPolicyWriteResponse: components["schemas"]["MessageResponse"] & components["schemas"]["EffectivePolicyResponse"];
        UserPolicyResponse: {
            policy: components["schemas"]["UserPolicyState"];
        };
        UserPolicyState: {
            policyKey: string;
            /** @enum {string} */
            scope: "user_policy";
            targetId: string;
            value: components["schemas"]["EffectivePolicyValue"];
            allowChildOverride: boolean;
        };
        UserPolicyWriteResponse: components["schemas"]["MessageResponse"] & components["schemas"]["UserPolicyResponse"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "admin-generate-certificate-cfssl": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description fields of root certificate */
                    rootCert: {
                        commonName: string;
                        names: {
                            [key: string]: {
                                value: string | string[];
                            };
                        };
                    };
                    /**
                     * @description URI of CFSSL API
                     * @default
                     */
                    cfsslUri?: string;
                    /**
                     * @description Path of config files of CFSSL
                     * @default
                     */
                    configPath?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["EngineHandlerResponse"];
                        };
                    };
                };
            };
            /** @description Account not found */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["MessageResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-generate-certificate-open-ssl": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description fields of root certificate */
                    rootCert: {
                        commonName: string;
                        names: {
                            [key: string]: {
                                value: string | string[];
                            };
                        };
                    };
                    /**
                     * @description Path of config files of CFSSL
                     * @default
                     */
                    configPath?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["EngineHandlerResponse"];
                        };
                    };
                };
            };
            /** @description Account not found */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["MessageResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-set-certificate-engine": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The certificate engine to use (openssl, cfssl, or none) */
                    engine: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CertificateEngineConfigResponse"];
                        };
                    };
                };
            };
            /** @description Invalid engine */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["MessageResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-load-certificate": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CertificateDataGenerated"];
                        };
                    };
                };
            };
        };
    };
    "admin-configure-check": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ConfigureChecksResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-signature-background-get": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    "admin-signature-background-save": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SuccessStatusResponse"];
                        };
                    };
                };
            };
            /** @description Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["FailureStatusResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-signature-background-delete": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted with success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SuccessStatusResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-save-certificate-policy": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CertificatePolicyResponse"];
                        };
                    };
                };
            };
            /** @description Upload or validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["FailureStatusResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-delete-certificate-policy": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** @enum {string} */
                                status: "success";
                            };
                        };
                    };
                };
            };
            /** @description Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["FailureStatusResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-update-oid": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description OID is a unique numeric identifier for certificate policies in digital certificates. */
                    oid: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SuccessStatusResponse"];
                        };
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["FailureStatusResponse"];
                        };
                    };
                };
            };
        };
    };
    "admin-get-active-signings": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active signings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ActiveSigningsResponse"];
                        };
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "crl_api-list": {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number | null;
                /** @description Number of items per page */
                length?: number | null;
                /** @description Filter by status (issued, revoked, expired) */
                status?: string | null;
                /** @description Filter by engine type */
                engine?: string | null;
                /** @description Filter by instance ID */
                instanceId?: string | null;
                /** @description Filter by generation */
                generation?: number | null;
                /** @description Filter by owner */
                owner?: string | null;
                /** @description Filter by serial number (partial match) */
                serialNumber?: string | null;
                /** @description Filter by who revoked the certificate */
                revokedBy?: string | null;
                /** @description Sort field (e.g., 'revoked_at', 'issued_at', 'serial_number') */
                sortBy?: string | null;
                /** @description Sort order (ASC or DESC) */
                sortOrder?: string | null;
            };
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CRL entries retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CrlListResponse"];
                        };
                    };
                };
            };
        };
    };
    "crl_api-revoke": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Certificate serial number to revoke */
                    serialNumber: string;
                    /**
                     * Format: int64
                     * @description Revocation reason code (0-10, see RFC 5280)
                     */
                    reasonCode?: number | null;
                    /** @description Optional text describing the reason */
                    reasonText?: string | null;
                };
            };
        };
        responses: {
            /** @description Certificate revoked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CrlRevokeResponse"];
                        };
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CrlRevokeResponse"];
                        };
                    };
                };
            };
            /** @description Certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CrlRevokeResponse"];
                        };
                    };
                };
            };
        };
    };
    "footer_template-get-footer-template": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["FooterTemplateResponse"];
                        };
                    };
                };
            };
        };
    };
    "footer_template-save-footer-template": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The Twig template to save (empty to reset to default)
                     * @default
                     */
                    template?: string;
                    /**
                     * Format: int64
                     * @description Width of preview in points (default: 595 - A4 width)
                     * @default 595
                     */
                    width?: number;
                    /**
                     * Format: int64
                     * @description Height of preview in points (default: 50)
                     * @default 50
                     */
                    height?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "policy-get-system": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Policy identifier to read from the system layer. */
                policyKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SystemPolicyResponse"];
                        };
                    };
                };
            };
        };
    };
    "policy-set-system": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Policy identifier to persist at the system layer. */
                policyKey: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Policy value to persist. Null resets the policy to its default system value. */
                    value?: (boolean | number | string | {
                        [key: string]: Record<string, never>;
                    }) | null;
                    /**
                     * @description Whether lower layers may override this system default.
                     * @default false
                     */
                    allowChildOverride?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SystemPolicyWriteResponse"];
                        };
                    };
                };
            };
            /** @description Invalid policy value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "policy-get-user-policy-for-user": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Target user identifier that receives the policy assignment. */
                userId: string;
                /** @description Policy identifier to read for the selected user. */
                policyKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["UserPolicyResponse"];
                        };
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "policy-set-user-policy-for-user": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Target user identifier that receives the policy assignment. */
                userId: string;
                /** @description Policy identifier to persist for the target user. */
                policyKey: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Policy value to persist as assigned target user policy. */
                    value?: (boolean | number | string | {
                        [key: string]: Record<string, never>;
                    }) | null;
                    /**
                     * @description Whether the target user may still override the assigned value in personal preferences.
                     * @default false
                     */
                    allowChildOverride?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["UserPolicyWriteResponse"];
                        };
                    };
                };
            };
            /** @description Invalid policy value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "policy-clear-user-policy-for-user": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Target user identifier that receives the policy assignment removal. */
                userId: string;
                /** @description Policy identifier to clear for the target user. */
                policyKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["UserPolicyWriteResponse"];
                        };
                    };
                };
            };
            /** @description User-scope not supported */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ErrorResponse"];
                        };
                    };
                };
            };
        };
    };
    "setting-has-root-cert": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["HasRootCertResponse"];
                        };
                    };
                };
            };
        };
    };
}
