# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

include:
  - path: ./ncdd.generated.yml

services:
  nextcloud:
    volumes:
      - ../:/var/www/html/apps-extra/libresign
  nginx:
    volumes:
      - ../:/var/www/html/apps-extra/libresign:ro
  playwright:
    volumes:
      - ../:/var/www/html/apps-extra/libresign
