
name: Changelog Reminder
on: pull_request

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: '/CHANGELOG.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the diff
      id: diff
      run: |
        git diff HEAD~1 -- CHANGELOG.md
        lines=$(git diff HEAD~1 -- CHANGELOG.md | wc -l)
        echo "::set-output name=lines::$lines"
    - name: Error if the number of diff lines is zero
      run: |
        echo "::error file=CHANGELOG.md::There was no change in the changelog detected. Please fill in a valid entry into that file."
        exit 1
      if: ${{ steps.diff.outputs.lines == 0 }}