name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror to GitLab
        run: |
          mkdir -p ~/.ssh
          echo "$INPUT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -Tvvv git@gitlab.com
          git remote add mirror git@gitlab.com:librecodecoop/libresign/libresign.git
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
