# SPDX-FileCopyrightText: 2025 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release Drafter

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - stable*
  pull_request_target:
    branches:
      - stable*
    types: [closed]

jobs:
  update_release_draft:
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/stable')) ||
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.base.ref, 'stable')
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Draft release for this branch
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
