# SPDX-FileCopyrightText: 2025-2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release Drafter

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - stable*

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v7.7.0
        with:
          config-name: release-drafter.yml
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
